  insertAtHead(tail ,head,25);
    print(head);
    insertAtHead(tail,head,26);
    print(head);
    insertAtTail(tail,head,46);
    print(head);
    insertAtTail(tail,head,46);
    print(head);
    insertAtPos(tail,head,6,34);
    print(head);
    insertAtPos(tail,head,7,30);
    print(head);